"""Speculative decoding engine.

Implements a draft-verify loop:

1. The **draft model** (small, fast) generates *k* candidate tokens.
2. The **target model** (large, slow) verifies each candidate in a single
   forward pass by generating the next token given the prompt + each prefix
   of the candidate sequence.
3. Accepted tokens are appended to the output; the first rejected token
   triggers re-drafting from the corrected position.

This approach can yield a measurable latency reduction when the acceptance
rate (``accepted / drafted``) is high — typically >0.5 for well-matched
draft/target model pairs.

Reference: Chen et al., "Accelerating Large Language Model Decoding with
Speculative Sampling", 2023 (https://arxiv.org/abs/2302.01318).
"""

from dataclasses import dataclass, field
from typing import Any

import structlog

from llm_inference_engine.integration.ollama_client import OllamaClient
from llm_inference_engine.optimization.draft_manager import DraftCandidate, DraftModelManager

logger = structlog.get_logger(__name__)


@dataclass
class SpeculationResult:
    """Result of a speculative decoding run.

    Attributes:
        text: The full generated text.
        total_tokens: Total tokens in the output.
        drafted_tokens: Total candidate tokens generated by the draft model.
        accepted_tokens: Candidate tokens accepted by the target model.
        rejected_tokens: Candidate tokens rejected by the target model.
        num_drafts: Number of draft-verify rounds performed.
        speedup_estimate: Rough estimate of speedup vs sequential decoding
            (``accepted_tokens / num_drafts`` per target call).
    """

    text: str
    total_tokens: int
    drafted_tokens: int
    accepted_tokens: int
    rejected_tokens: int
    num_drafts: int
    speedup_estimate: float = field(init=False)

    def __post_init__(self) -> None:
        if self.num_drafts > 0 and self.drafted_tokens > 0:
            # Each target call accepts on average this many tokens instead of 1.
            self.speedup_estimate = max(1.0, self.accepted_tokens / max(1, self.num_drafts))
        else:
            self.speedup_estimate = 1.0

    @property
    def acceptance_rate(self) -> float:
        """Fraction of drafted tokens accepted by the target model."""
        if self.drafted_tokens == 0:
            return 0.0
        return self.accepted_tokens / self.drafted_tokens


class SpeculationEngine:
    """Draft-verify speculative decoding engine.

    Uses a small draft model to pre-generate candidate tokens and a large
    target model to verify them, accepting or rejecting each candidate.

    Usage::

        engine = SpeculationEngine(
            target_client=target_client,
            draft_manager=DraftModelManager(draft_client, "phi3:mini"),
            target_model="llama3.1:8b",
            max_output_tokens=256,
        )
        result = await engine.generate("The quick brown fox")
        print(result.text)
        print(f"Speedup: {result.speedup_estimate:.2f}x")
    """

    def __init__(
        self,
        target_client: OllamaClient,
        draft_manager: DraftModelManager,
        target_model: str,
        max_output_tokens: int = 256,
        max_rounds: int = 64,
        temperature: float = 0.0,
    ) -> None:
        """Initialise the speculation engine.

        Args:
            target_client: Ollama client for the target (large) model.
            draft_manager: :class:`~llm_inference_engine.optimization.\
draft_manager.DraftModelManager` wrapping the small draft model.
            target_model: Tag of the target model (verifier).
            max_output_tokens: Maximum total output tokens.
            max_rounds: Maximum draft-verify rounds (guards against infinite loops).
            temperature: Target model sampling temperature (0 = greedy).
        """
        if max_output_tokens <= 0:
            raise ValueError("max_output_tokens must be positive")
        if max_rounds <= 0:
            raise ValueError("max_rounds must be positive")
        self._target_client = target_client
        self._draft_manager = draft_manager
        self._target_model = target_model
        self._max_output_tokens = max_output_tokens
        self._max_rounds = max_rounds
        self._temperature = temperature
        logger.info(
            "speculation_engine_initialized",
            target_model=target_model,
            draft_model=draft_manager.draft_model,
            max_output_tokens=max_output_tokens,
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def generate(self, prompt: str) -> SpeculationResult:
        """Generate text using the draft-verify loop.

        Args:
            prompt: The input prompt.

        Returns:
            A :class:`SpeculationResult` with the generated text and
            acceptance statistics.
        """
        output_tokens: list[str] = []
        current_prompt = prompt
        drafted_total = 0
        accepted_total = 0
        rejected_total = 0
        num_drafts = 0

        for _ in range(self._max_rounds):
            if len(output_tokens) >= self._max_output_tokens:
                break

            # 1. Draft step.
            candidate = await self._draft_manager.generate_draft(current_prompt)
            num_drafts += 1
            if not candidate.tokens:
                break

            drafted_total += candidate.length

            # 2. Verify step.
            accepted, correction = await self._verify(current_prompt, candidate)
            accepted_total += len(accepted)
            rejected_total += candidate.length - len(accepted)

            output_tokens.extend(accepted)
            current_prompt = current_prompt + "".join(accepted)

            if correction:
                output_tokens.append(correction)
                current_prompt += correction

            # Stop if target returned a stop token.
            if not accepted and not correction:
                break

        text = "".join(output_tokens)
        result = SpeculationResult(
            text=text,
            total_tokens=len(output_tokens),
            drafted_tokens=drafted_total,
            accepted_tokens=accepted_total,
            rejected_tokens=rejected_total,
            num_drafts=num_drafts,
        )
        logger.info(
            "speculation_complete",
            total_tokens=result.total_tokens,
            acceptance_rate=round(result.acceptance_rate, 3),
            speedup_estimate=round(result.speedup_estimate, 2),
            num_drafts=num_drafts,
        )
        return result

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    async def _verify(
        self, prompt: str, candidate: DraftCandidate
    ) -> tuple[list[str], str | None]:
        """Verify *candidate* tokens against the target model.

        For each prefix of the candidate sequence the target model predicts
        the next token.  Candidates are accepted as long as the target
        model agrees; the first disagreement triggers a correction.

        This implementation uses a simplified greedy heuristic: we call
        the target model once for the full candidate and compare the
        target's output against the candidate token-by-token.

        Args:
            prompt: Current prompt (without candidate tokens).
            candidate: Draft candidate tokens to verify.

        Returns:
            Tuple of (accepted_tokens, correction_token).
            ``correction_token`` is the target model's correction at the
            first rejection point, or ``None`` if all tokens were accepted.
        """
        # Ask the target model to continue from the same prompt.
        raw: dict[str, Any] = await self._target_client.generate(
            model=self._target_model,
            prompt=prompt,
            max_tokens=candidate.length + 1,
            temperature=self._temperature,
        )
        target_text = str(raw.get("response", ""))
        target_tokens = self._draft_manager._split_tokens(target_text)  # noqa: SLF001

        accepted: list[str] = []
        correction: str | None = None

        for i, draft_tok in enumerate(candidate.tokens):
            if i >= len(target_tokens):
                break
            target_tok = target_tokens[i]
            # Compare after stripping surrounding whitespace only.
            # Do NOT normalise case: "The" and "the" are distinct tokens
            # and accepting them interchangeably degrades output quality.
            if draft_tok.strip() == target_tok.strip():
                accepted.append(draft_tok)
            else:
                correction = target_tok
                break

        return accepted, correction


__all__ = ["SpeculationEngine", "SpeculationResult"]
